### ISSUE TITLE
List of Peers/Nodes to connect to?

### ISSUE THREAD

**Issue by NoWay426** [DAGBPA/BitcoinPizza#3]
My client is only connecting to one peer, if somebody could post a list of known peers that would be very helpful.

**Comment by xilin** [comment]
@NoWay426 

node1 华东 2 可用区 A 101.132.180.96

node2 华东 2 可用区 A 101.132.125.68

node3 亚太东北1 可用区A 东京 47.74.6.39

node4 香港可用区C 47.91.209.188

node5 亚太东南1 可用区A 新加坡 47.74.180.81

node6 华东 2 可用区 A 47.100.55.227



idc1 60.223.237.151  （建议大陆使用该节点）



europe1 89.38.97.62 Netherlands

europe2 46.28.204.17 Sweden

Some nodes with Chinese comments maybe only available in China
