### ISSUE TITLE
how to startup rpc server?

### ISSUE THREAD

**Issue by Edward-Roshan** [DAGBPA/BitcoinPizza#6]
I set up Z-nomp. But it shows that I need run rpc server to support payment processor. Please help me how could I startup rpc. is it just startup full node gui or daemon? could you help me?

**Comment by DAGBPA** [comment]
You need to run a full node daemon.
And in the config file '~/.bitcoinpizza/bitcoinpizza.conf', you need to add some settings to enable RPC:

server=1  
rpcuser=demo
rpcpassword=demo
rpcport=8332
